language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: xb5G0Flp4mlzgWuKs5AP1AaAoCXesiDOQJJK7e9TF9v9yGFxFMIhqag92/Hwo4lMiJmqy63rhiU/yS0Ck+yAFwmEW8f5UvPwLl8Zxt9xGCh0OtsxwvJag9007Vg1lWYiRXfAmyD7ca4CXlUGQJdtXqCxnasQFdtFudgEhkT5h06tZWawCoezczgXlsHJ+oZPca/Z7OssWCC/NEmciCvqcmrSipPi3KqBZrhyZmBDYbe7C4KXyi7K07WfeDV9pWkk1VowHetWWg0/x1piPp+r+NKePGONxzZF98fr+4vL2mmGrjBO76ytIrAH7Rc6SVdINBytwb7D6+zYNFW25eyWdwSB5aiu163294z5NI1lv3QNQWNHKbOf6MmcOUP0HqcsGeP/XAH/emsffxG3aVqVrEwh+jqWnswo0ahE0gbk2WcQnJhSi4N6WV2rgCrhem9mac8LFOAwE1uRZyJCN6FS7pa1qCVsmPFo++asc1BDgWB1v7W9UlmR7W364lFmkpI9kaaXeFaYQ+VT6f5B8yhNk/2Bre+nGor1fRw/zT0xn/KUBlqYLLoyEPcWwavmkt9Wn+yYcj/Lst4MRqoH0EBHlXRHsypdj6CPXDnm6xTkBhNOx6KHEUWj2GzFasSLorK2Y/K07FhQx6DK6xvILGibAu9xFHG98hssTYNKAlrP27I=
  - secure: vfuMB5gE+KsW8rlQoxhr+vcZXH4ymtqZ0G6u7CYOdCFuCM+4nxsXVspppHcgHA1woGQfJ03N8hanOWEKc0H2qB2/nEDqUXRM9fnARnx6oKbhykyVGLQPBXfGtED2Kp29yz22823l20P5V6Dmv8M73zrQTzATnG0TszflcXEFCkQuF/iRLM2bbGrQmk6PfuGCB9DO9XJ0k7PdbKOkqGWiLS8Yikdzib3XGW9hJWlouIlm1nc5mOFR9SWOLLmOHTLuAFOBSS64+NeqEnAnwjepWtfI78NlkpYXALz9aShF7HTR/nNAKuWs2RN2o/cmqxtFXxS+X55EnhLlxJ6WvWVizWKcyk2QLmasijR0IQtjm97D1OVHalsY6LGDh+UBto/k9hZeQC3kMEPYPDMd1SHbjdgj8w0R3r23xyNy0fDCH3C7XLWjXhEtOYJAON/u4+UH5aSa4HdO7gCCUt0w+3qUmtFTSh8n5D8NMu4LTpwgAj9wW4v8TyMqpxW+OWNnaFbI3sNEqGwaYApNevfF6AR7s1Lghir5ZQPkoG8xFhV1s+qEI0AuIRJ+/Mtpf0KmJ10DwP3glZ8sGV7BSwzHCo97b8NNPIoDVTuuD+uJOw2gB78Gq7SBbEKd8u0zvc9+8rlUiU8FIHEfB3wBe2eHi27cXwg1EHqgAkioGDzL0rIS0Ys=
  - secure: WqQ49chnSDsdTGHivJFoNldI/Wyy9mIKdnp3OeVeX7G7mGzedPYNOwWaQNryuUttV1MmK2c1h2M9E3PIPBdrFEpP2R93htz6u+FnemDOPL/kdGk7siKyq9v9sWfA5Lj5jbeqR4EPo0QwhcSnuwzSj7AItYbiG1Lv+sXZ/S6N73lr3fjnKDNGQsMd+LEsBVWtf7mgyWe5HCBHAMU/pZdmIP+2GyG/0WUA4L3EX+X5vfeFA2ZAFNTR03hfd4nvMBYcwM3+lelY5698nSkfwQk6MejIbAyoj6tv8/3zC4z3PaLTCn/nrRgHvF12/7rQ1WB4B6djqjtdrKFjiaQr5kE+I7ptcOsF6RGPCwEiQJK/NUWpfAy3/9WIUFh+Ux/NirILL+U6WLPgPKfxjGK9a+w9m3O9jnhwDVhCPJ9N9A1I6w20TQVxHh8vbT8KP1Bo4hkU/SSBkDqLtgh5hC04/2A1pl+GdJWio4Iqs+Q6JpxvSdqpt5JKWuwgquJwT9ovW9Uqe0/ZAM9PXAP2yw/7fjAdn9WcpEuATNJQBMDu3e8/JYhzijD2cnCS+wFmOF+1XWvlr88512TWa5EYEcndwVgJqXqvobWWWGHr8oCSgqXyf2//yCShLfWO3CvzfJ/qpLQAU/cQoD/MevVYm3QuptwIDWPbqjH+8jiVA75GQRtVSiQ=

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
